version: 0.2
env:
  variables:
    REGION: ap-south-1
    REPO: brain-tasks-app

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO}
      - aws ecr describe-repositories --repository-names ${REPO} --region ${REGION} || aws ecr create-repository --repository-name ${REPO} --region ${REGION}
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ${REPO}:${COMMIT_ID} .
      - docker tag ${REPO}:${COMMIT_ID} ${ECR_URI}:${COMMIT_ID}
  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push ${ECR_URI}:${COMMIT_ID}
      - echo "IMAGE_TAG=${COMMIT_ID}" > image_tag.env
artifacts:
  files:
    - image_tag.env
    - k8s/deployment.yaml
    - k8s/service.yaml
  discard-paths: no
